# -*- Makefile -*-
### Makefile - VHDL Makefile generated by Emacs VHDL Mode 3.33.6

# Directory : "~/Documents/nyit/CSCI641/mips_cpu/"
# Platform  : ModelSim
# Generated : 2012-04-02 08:45:59 vnayar


# Define compilation command and options

COMPILE = vcom
OPTIONS = -93 -work work


# Define library paths

LIBRARY-work = work


# Define library unit files

UNIT-work-adder = \
	$(LIBRARY-work)/adder/_primary.dat
UNIT-work-adder-behavioral = \
	$(LIBRARY-work)/adder/behavioral.dat
UNIT-work-alu = \
	$(LIBRARY-work)/alu/_primary.dat
UNIT-work-alu-behavioral = \
	$(LIBRARY-work)/alu/behavioral.dat
UNIT-work-aludecoder = \
	$(LIBRARY-work)/aludecoder/_primary.dat
UNIT-work-aludecoder-synth = \
	$(LIBRARY-work)/aludecoder/synth.dat
UNIT-work-controlunit = \
	$(LIBRARY-work)/controlunit/_primary.dat
UNIT-work-controlunit-struct = \
	$(LIBRARY-work)/controlunit/struct.dat
UNIT-work-lshift = \
	$(LIBRARY-work)/lshift/_primary.dat
UNIT-work-lshift-synth = \
	$(LIBRARY-work)/lshift/synth.dat
UNIT-work-maindecoder = \
	$(LIBRARY-work)/maindecoder/_primary.dat
UNIT-work-maindecoder-synth = \
	$(LIBRARY-work)/maindecoder/synth.dat
UNIT-work-mips_top = \
	$(LIBRARY-work)/mips_top/_primary.dat
UNIT-work-mips_top-synth = \
	$(LIBRARY-work)/mips_top/synth.dat
UNIT-work-mipstop = \
	$(LIBRARY-work)/mipstop/_primary.dat
UNIT-work-mipstop-structure = \
	$(LIBRARY-work)/mipstop/structure.dat
UNIT-work-mux2 = \
	$(LIBRARY-work)/mux2/_primary.dat
UNIT-work-mux2-synth = \
	$(LIBRARY-work)/mux2/synth.dat
UNIT-work-pcounter = \
	$(LIBRARY-work)/pcounter/_primary.dat
UNIT-work-pcounter-behavioral = \
	$(LIBRARY-work)/pcounter/behavioral.dat
UNIT-work-ram = \
	$(LIBRARY-work)/ram/_primary.dat
UNIT-work-ram-behavior = \
	$(LIBRARY-work)/ram/behavior.dat
UNIT-work-registerfile = \
	$(LIBRARY-work)/registerfile/_primary.dat
UNIT-work-registerfile-behavior = \
	$(LIBRARY-work)/registerfile/behavior.dat
UNIT-work-rom = \
	$(LIBRARY-work)/rom/_primary.dat
UNIT-work-rom-behavior = \
	$(LIBRARY-work)/rom/behavior.dat
UNIT-work-signextend = \
	$(LIBRARY-work)/signextend/_primary.dat
UNIT-work-signextend-behaviour = \
	$(LIBRARY-work)/signextend/behaviour.dat
UNIT-work-sort_mips = \
	$(LIBRARY-work)/sort_mips/_primary.dat
UNIT-work-sort_mips-structure = \
	$(LIBRARY-work)/sort_mips/structure.dat
UNIT-work-tb_mips = \
	$(LIBRARY-work)/tb_mips/_primary.dat
UNIT-work-tb_mips-structure = \
	$(LIBRARY-work)/tb_mips/structure.dat
UNIT-work-tb_mips_generator = \
	$(LIBRARY-work)/tb_mips_generator/_primary.dat
UNIT-work-tb_mips_generator-testbench_gen = \
	$(LIBRARY-work)/tb_mips_generator/testbench_gen.dat


# Define list of all library unit files

ALL_UNITS = \
	$(UNIT-work-adder) \
	$(UNIT-work-adder-behavioral) \
	$(UNIT-work-alu) \
	$(UNIT-work-alu-behavioral) \
	$(UNIT-work-aludecoder) \
	$(UNIT-work-aludecoder-synth) \
	$(UNIT-work-controlunit) \
	$(UNIT-work-controlunit-struct) \
	$(UNIT-work-lshift) \
	$(UNIT-work-lshift-synth) \
	$(UNIT-work-maindecoder) \
	$(UNIT-work-maindecoder-synth) \
	$(UNIT-work-mips_top) \
	$(UNIT-work-mips_top-synth) \
	$(UNIT-work-mipstop) \
	$(UNIT-work-mipstop-structure) \
	$(UNIT-work-mux2) \
	$(UNIT-work-mux2-synth) \
	$(UNIT-work-pcounter) \
	$(UNIT-work-pcounter-behavioral) \
	$(UNIT-work-ram) \
	$(UNIT-work-ram-behavior) \
	$(UNIT-work-registerfile) \
	$(UNIT-work-registerfile-behavior) \
	$(UNIT-work-rom) \
	$(UNIT-work-rom-behavior) \
	$(UNIT-work-signextend) \
	$(UNIT-work-signextend-behaviour) \
	$(UNIT-work-sort_mips) \
	$(UNIT-work-sort_mips-structure) \
	$(UNIT-work-tb_mips) \
	$(UNIT-work-tb_mips-structure) \
	$(UNIT-work-tb_mips_generator) \
	$(UNIT-work-tb_mips_generator-testbench_gen)



# Rule for compiling entire design

all : \
		library \
		$(ALL_UNITS)


# Rule for cleaning entire design

clean : 
	-rm -f $(ALL_UNITS)


# Rule for creating library directory

library : \
		$(LIBRARY-work)

$(LIBRARY-work) :
	vlib $(LIBRARY-work); vmap work $(LIBRARY-work)


# Rules for compiling single library units and their subhierarchy

adder : \
		library \
		$(UNIT-work-adder) \
		$(UNIT-work-adder-behavioral)

alu \
ALU : \
		library \
		$(UNIT-work-alu) \
		$(UNIT-work-alu-behavioral)

aludecoder \
ALUDecoder : \
		library \
		$(UNIT-work-aludecoder) \
		$(UNIT-work-aludecoder-synth)

controlunit \
ControlUnit : \
		library \
		$(UNIT-work-controlunit) \
		$(UNIT-work-controlunit-struct) \
		aludecoder \
		maindecoder

lshift : \
		library \
		$(UNIT-work-lshift) \
		$(UNIT-work-lshift-synth)

maindecoder \
MainDecoder : \
		library \
		$(UNIT-work-maindecoder) \
		$(UNIT-work-maindecoder-synth)

mips_top : \
		library \
		$(UNIT-work-mips_top) \
		$(UNIT-work-mips_top-synth) \
		adder \
		alu \
		controlunit \
		lshift \
		mux2 \
		pcounter \
		ram \
		registerfile \
		signextend

mipstop : \
		library \
		$(UNIT-work-mipstop) \
		$(UNIT-work-mipstop-structure) \
		alu \
		pcounter \
		ram \
		registerfile \
		rom

mux2 \
Mux2 : \
		library \
		$(UNIT-work-mux2) \
		$(UNIT-work-mux2-synth)

pcounter \
PCounter : \
		library \
		$(UNIT-work-pcounter) \
		$(UNIT-work-pcounter-behavioral)

ram \
RAM : \
		library \
		$(UNIT-work-ram) \
		$(UNIT-work-ram-behavior)

registerfile : \
		library \
		$(UNIT-work-registerfile) \
		$(UNIT-work-registerfile-behavior)

rom \
ROM : \
		library \
		$(UNIT-work-rom) \
		$(UNIT-work-rom-behavior)

signextend \
SignExtend : \
		library \
		$(UNIT-work-signextend) \
		$(UNIT-work-signextend-behaviour)

sort_mips : \
		library \
		$(UNIT-work-sort_mips) \
		$(UNIT-work-sort_mips-structure) \
		mips_top \
		rom \
		tb_mips_generator

tb_mips : \
		library \
		$(UNIT-work-tb_mips) \
		$(UNIT-work-tb_mips-structure) \
		mips_top \
		rom \
		tb_mips_generator

tb_mips_generator : \
		library \
		$(UNIT-work-tb_mips_generator) \
		$(UNIT-work-tb_mips_generator-testbench_gen)


# Rules for compiling single library unit files

$(UNIT-work-adder) \
$(UNIT-work-adder-behavioral) : \
		adder.vhd
	$(COMPILE) $(OPTIONS) adder.vhd

$(UNIT-work-alu) \
$(UNIT-work-alu-behavioral) : \
		alu.vhd
	$(COMPILE) $(OPTIONS) alu.vhd

$(UNIT-work-aludecoder) \
$(UNIT-work-aludecoder-synth) : \
		alu_decoder.vhd
	$(COMPILE) $(OPTIONS) alu_decoder.vhd

$(UNIT-work-controlunit) \
$(UNIT-work-controlunit-struct) : \
		control_unit.vhd \
		$(UNIT-work-aludecoder) \
		$(UNIT-work-maindecoder)
	$(COMPILE) $(OPTIONS) control_unit.vhd

$(UNIT-work-lshift) \
$(UNIT-work-lshift-synth) : \
		lshift.vhd
	$(COMPILE) $(OPTIONS) lshift.vhd

$(UNIT-work-maindecoder) \
$(UNIT-work-maindecoder-synth) : \
		main_decoder.vhd
	$(COMPILE) $(OPTIONS) main_decoder.vhd

$(UNIT-work-mips_top) \
$(UNIT-work-mips_top-synth) : \
		mips_top.vhd \
		$(UNIT-work-adder) \
		$(UNIT-work-alu) \
		$(UNIT-work-controlunit) \
		$(UNIT-work-lshift) \
		$(UNIT-work-mux2) \
		$(UNIT-work-pcounter) \
		$(UNIT-work-ram) \
		$(UNIT-work-registerfile) \
		$(UNIT-work-signextend)
	$(COMPILE) $(OPTIONS) mips_top.vhd

$(UNIT-work-mipstop) \
$(UNIT-work-mipstop-structure) : \
		mipstop.vhd \
		$(UNIT-work-alu) \
		$(UNIT-work-pcounter) \
		$(UNIT-work-ram) \
		$(UNIT-work-registerfile) \
		$(UNIT-work-rom)
	$(COMPILE) $(OPTIONS) mipstop.vhd

$(UNIT-work-mux2) \
$(UNIT-work-mux2-synth) : \
		mux2.vhd
	$(COMPILE) $(OPTIONS) mux2.vhd

$(UNIT-work-pcounter) \
$(UNIT-work-pcounter-behavioral) : \
		PCounter.vhd
	$(COMPILE) $(OPTIONS) PCounter.vhd

$(UNIT-work-ram) \
$(UNIT-work-ram-behavior) : \
		RAM.vhd
	$(COMPILE) $(OPTIONS) RAM.vhd

$(UNIT-work-registerfile) \
$(UNIT-work-registerfile-behavior) : \
		registerfile.vhd
	$(COMPILE) $(OPTIONS) registerfile.vhd

$(UNIT-work-rom) \
$(UNIT-work-rom-behavior) : \
		ROM.vhd
	$(COMPILE) $(OPTIONS) ROM.vhd

$(UNIT-work-signextend) \
$(UNIT-work-signextend-behaviour) : \
		SignExtend.vhd
	$(COMPILE) $(OPTIONS) SignExtend.vhd

$(UNIT-work-sort_mips) \
$(UNIT-work-sort_mips-structure) : \
		sort_mips.vhd \
		$(UNIT-work-mips_top) \
		$(UNIT-work-rom) \
		$(UNIT-work-tb_mips_generator)
	$(COMPILE) $(OPTIONS) sort_mips.vhd

$(UNIT-work-tb_mips) \
$(UNIT-work-tb_mips-structure) : \
		tb_mips.vhd \
		$(UNIT-work-mips_top) \
		$(UNIT-work-rom) \
		$(UNIT-work-tb_mips_generator)
	$(COMPILE) $(OPTIONS) tb_mips.vhd

$(UNIT-work-tb_mips_generator) \
$(UNIT-work-tb_mips_generator-testbench_gen) : \
		tb_mips_generator.vhd
	$(COMPILE) $(OPTIONS) tb_mips_generator.vhd


### Makefile ends here
